services:
    api:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.librechat.rule=Host(`chat.goochem.dev`)"
        - "traefik.http.routers.librechat.entrypoints=websecure"
        - "traefik.http.routers.librechat.tls.certresolver=cloudflare"
        - "traefik.http.services.librechat.loadbalancer.server.port=3080"
      networks:
        - librechat_default
        - proxy_network
      volumes:
        - ./librechat.yaml:/app/librechat.yaml
  
# other configs here #
 
# NOTE: This needs to be at the bottom of your docker-compose.override.yml
networks:
  proxy_network:
    external: true

  librechat_default:
    external: true
